from agent.protocols.guards import (
    LOOP_NUDGE_TEMPLATE,
    LOOP_STOP_TEMPLATE,
    NON_SHELL_BLOCK_TEMPLATE,
    REASONING_NUDGE_TEMPLATE,
    coerce_to_schema,
    collapse_repeats,
    json_schema_of,
    looks_like_preamble,
    looks_like_tool_attempt,
    needs_command_retry,
    non_shell_block_lang,
    trailing_repeated_thoughts,
    trailing_repeats,
)
from agent.protocols.history import king_messages
from agent.protocols.parse import (
    COMPLETE_MARKER,
    DONE_TEXT,
    RC_SUFFIX,
    parse_reply,
    render_observation,
    split_rc,
)
from agent.protocols.reply import agent_reply
from agent.protocols.tools import (
    HINT_TEMPLATE,
    POWERSHELL_HINT,
    SHELL_TOOL_NAMES,
    ShellTool,
    build_args,
    detect_powershell,
    find_shell_tool,
    shell_lang,
    tool_hint,
)

__all__ = [
    "COMPLETE_MARKER",
    "DONE_TEXT",
    "HINT_TEMPLATE",
    "LOOP_NUDGE_TEMPLATE",
    "LOOP_STOP_TEMPLATE",
    "NON_SHELL_BLOCK_TEMPLATE",
    "POWERSHELL_HINT",
    "RC_SUFFIX",
    "REASONING_NUDGE_TEMPLATE",
    "SHELL_TOOL_NAMES",
    "ShellTool",
    "agent_reply",
    "build_args",
    "coerce_to_schema",
    "collapse_repeats",
    "detect_powershell",
    "find_shell_tool",
    "json_schema_of",
    "king_messages",
    "looks_like_preamble",
    "looks_like_tool_attempt",
    "needs_command_retry",
    "non_shell_block_lang",
    "parse_reply",
    "render_observation",
    "shell_lang",
    "split_rc",
    "tool_hint",
    "trailing_repeated_thoughts",
    "trailing_repeats",
]
